version: '3'
services:
  web:
    build: app
    ports:
      - "80"
    network_mode: host
    env_file:
      - "./.envrc"
  couch:
    build: couchdb
    ports:
      - "127.0.0.1:5984:5984"
    env_file:
      - "./.envrc"
